// Grade-receipt contract: the modal behind the hero's grade circle mirrors
// the engine's dock math from the published rows, reconciles every derived
// number against the published grade block, and degrades to bucket-level
// (verified:false, no per-item points) on any mismatch. Every fixture's
// grade block here was generated by the REAL engine (cf_lib.facility_grade)
// from these exact inspection docs — engine-certified, not hand-trusted.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const source = readFileSync(
    new URL('../public/static/js/foodDashboard.js', import.meta.url),
    'utf8',
);
const css = readFileSync(
    new URL('../public/static/css/style.css', import.meta.url),
    'utf8',
);
const dashboard = await import(
    `data:text/javascript;base64,${Buffer.from(source).toString('base64')}`
);

const { gradeReceiptPresentation } = dashboard;

// ── engine-certified fixtures ───────────────────────────────────────────

// Case A — unadjusted: repeat-in-text + corrected-on-site on the base.
const baseA = {
    inspection_id: 'B1', date: '2026-03-01', scope: 'broad', score: 85,
    checklist: [
        { item: 8, disposition: 'OUT', violation: true, cos: true },
        { item: 14, disposition: 'OUT', violation: true },
        { item: 35, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 8, text: 'Raw chicken stored over ready-to-eat lettuce' },
        { item: 14, text: 'repeat: handwashing sink blocked by cart' },
        { item: 35, text: 'Floor grout worn behind the line' },
    ],
};
const gradeA = {
    score: 85, letter: 'B', base_score: 85, base_letter: 'B',
    base_date: '2026-03-01', base_inspection_id: 'B1', adjusted: false,
    followups: 0, followup_date: null, narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 0.0,
};

// Case B — adjusted mixed: one restored, one failed, one new-with-repeat,
// one unchecked. Ledger cannot visibly sum (88 + 2.9 − 12 = 78.9 vs 78).
const baseB = {
    inspection_id: 'B1', date: '2026-03-01', scope: 'broad', score: 88,
    checklist: [
        { item: 8, disposition: 'OUT', violation: true, cos: true },
        { item: 14, disposition: 'OUT', violation: true },
        { item: 35, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 8, text: 'Raw chicken stored over ready-to-eat lettuce' },
        { item: 14, text: 'Handwashing sink blocked by cart' },
        { item: 35, text: 'Floor grout worn behind the line' },
    ],
};
const fupB = {
    inspection_id: 'F1', date: '2026-04-01', scope: 'focused',
    purpose: 'Follow-Up', score: 94,
    checklist: [
        { item: 8, disposition: 'IN', compliant: true },
        { item: 14, disposition: 'OUT', violation: true },
        { item: 22, disposition: 'OUT', violation: true, repeat: true },
    ],
    violations: [
        { item: 14, text: 'Sink still blocked' },
        { item: 22, text: 'Sanitizer bucket at 0 ppm, repeat noted' },
    ],
};
const gradeB = {
    score: 78, letter: 'C', base_score: 88, base_letter: 'B',
    base_date: '2026-03-01', base_inspection_id: 'B1', adjusted: true,
    followups: 1, followup_date: '2026-04-01', narrative_followups: 0,
    narrative_items: [], restored_items: [8], failed_items: [14],
    cos_items: [], new_items: [22], unchecked_items: [35],
    restored_points: 2.9, extra_points: 12.0,
};

// Case C — narrative blanket clear: both docks restored by the written verdict.
const baseC = {
    inspection_id: 'B2', date: '2026-02-09', scope: 'broad', score: 88,
    checklist: [{ item: 8, disposition: 'OUT', violation: true },
        { item: 21, disposition: 'OUT', violation: true }],
    violations: [
        { item: 8, text: 'No soap at handwash station' },
        { item: 21, text: 'Cold holding at 47F' },
    ],
};
const narrC = {
    inspection_id: 'N1', date: '2026-04-06', scope: 'unknown',
    purpose: 'Follow-Up', score: 100, checklist: [], violations: [],
    adjudication: { status: 'adjudicated', verdict: 'all_corrected' },
};
const gradeC = {
    score: 96, letter: 'A', base_score: 88, base_letter: 'B',
    base_date: '2026-02-09', base_inspection_id: 'B2', adjusted: true,
    followups: 1, followup_date: '2026-04-06', narrative_followups: 1,
    narrative_items: [8, 21], restored_items: [8, 21], failed_items: [],
    cos_items: [], new_items: [], unchecked_items: [],
    restored_points: 7.8, extra_points: 0.0,
};

// Case E — same-day gating: a same-day focused visit adjusts ONLY when its
// purpose marks it a Follow-Up (VDH dates carry no time).
const baseE = {
    inspection_id: 'B3', date: '2026-05-01', scope: 'broad', score: 98,
    checklist: [{ item: 35, disposition: 'OUT', violation: true }],
    violations: [{ item: 35, text: 'Dusty vent hood' }],
};
const sameDay = (purpose) => ({
    inspection_id: 'F2', date: '2026-05-01', scope: 'focused', purpose,
    score: 100, checklist: [{ item: 35, disposition: 'IN', compliant: true }], violations: [],
});
const gradeE1 = {
    score: 98, letter: 'A', base_score: 98, base_letter: 'A',
    base_date: '2026-05-01', base_inspection_id: 'B3', adjusted: false,
    followups: 0, followup_date: null, narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 0.0,
};
const gradeE2 = {
    score: 99, letter: 'A', base_score: 98, base_letter: 'A',
    base_date: '2026-05-01', base_inspection_id: 'B3', adjusted: true,
    followups: 1, followup_date: '2026-05-01', narrative_followups: 0,
    narrative_items: [], restored_items: [35], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 1.3, extra_points: 0.0,
};

// Case F — OUT+COS on a re-check: base credit revoked, full weight, no mult.
const baseF = {
    inspection_id: 'B4', date: '2026-01-10', scope: 'broad', score: 96,
    checklist: [{ item: 8, disposition: 'OUT', violation: true, cos: true }],
    violations: [{ item: 8, text: 'Raw over RTE' }],
};
const fupF = {
    inspection_id: 'F3', date: '2026-02-10', scope: 'focused',
    purpose: 'Follow-Up', score: 94,
    checklist: [{ item: 8, disposition: 'OUT', violation: true, cos: true }],
    violations: [{ item: 8, text: 'Raw over RTE again, moved on the spot' }],
};
const gradeF = {
    score: 94, letter: 'A', base_score: 96, base_letter: 'A',
    base_date: '2026-01-10', base_inspection_id: 'B4', adjusted: true,
    followups: 1, followup_date: '2026-02-10', narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [8],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 1.5,
};

// ── tests ───────────────────────────────────────────────────────────────

test('no grade → no receipt', () => {
    assert.equal(gradeReceiptPresentation({}, []), null);
    assert.equal(gradeReceiptPresentation({ grade: null }, []), null);
});

test('unadjusted receipt verifies and itemizes the base docks', () => {
    const r = gradeReceiptPresentation({ grade: gradeA }, [baseA]);
    assert.equal(r.verified, true);
    assert.equal(r.adjusted, false);
    assert.equal(r.base.found, true);
    assert.equal(r.base.score, 85);
    assert.equal(r.base.items.length, 3);
    const [i8, i14, i35] = r.base.items;
    assert.deepEqual(
        { item: i8.item, points: i8.points, cos: i8.cos, category: i8.category },
        { item: 8, points: 4.5, cos: true, category: 'risk_factor' });
    // repeat detected from the observation TEXT, not just the checklist flag
    assert.deepEqual({ item: i14.item, points: i14.points, repeat: i14.repeat },
        { item: 14, points: 9, repeat: true });
    assert.deepEqual({ item: i35.item, points: i35.points, category: i35.category },
        { item: 35, points: 2, category: 'grp' });
    assert.equal(r.followups.length, 0);
});

test('adjusted receipt derives every journey and reconciles', () => {
    const r = gradeReceiptPresentation({ grade: gradeB }, [fupB, baseB]);
    assert.equal(r.verified, true);
    assert.equal(r.adjusted, true);
    assert.equal(r.followups.length, 1);
    assert.equal(r.followups[0].kind, 'checklist');
    assert.equal(r.followups[0].label, '2/3 OUT');

    const restored = r.journeys.restored[0];
    assert.deepEqual(
        { item: restored.item, delta: restored.delta, dockPts: restored.dockPts },
        { item: 8, delta: 2.9, dockPts: 4.5 });   // 65% of the 4.5 COS'd dock
    const failed = r.journeys.failed[0];
    assert.deepEqual({ item: failed.item, delta: failed.delta },
        { item: 14, delta: 3 });                   // 9 charged − 6 base = 3 more
    const fresh = r.journeys.new[0];
    assert.deepEqual({ item: fresh.item, delta: fresh.delta, repeat: fresh.repeat },
        { item: 22, delta: 9, repeat: true });     // RF × 1.5 repeat flag
    assert.equal(fresh.text, 'Sanitizer bucket at 0 ppm, repeat noted');
    const stands = r.journeys.unchecked[0];
    assert.deepEqual({ item: stands.item, dockPts: stands.dockPts },
        { item: 35, dockPts: 2 });

    // 88 + 2.9 − 12 = 78.9 ≠ 78: the round-once footnote must appear.
    assert.equal(r.ledger.exact, false);
    assert.deepEqual(
        { base: r.ledger.baseScore, restored: r.ledger.restored, added: r.ledger.added, score: r.ledger.score },
        { base: 88, restored: 2.9, added: 12, score: 78 });
});

test('narrative blanket clear restores at par and is flagged per item', () => {
    const r = gradeReceiptPresentation({ grade: gradeC }, [narrC, baseC]);
    assert.equal(r.verified, true);
    assert.equal(r.followups[0].kind, 'narrative');
    assert.equal(r.followups[0].label, 'All violations corrected');
    assert.equal(r.journeys.restored.length, 2);
    for (const row of r.journeys.restored) {
        assert.equal(row.narrative, true);
        assert.equal(row.delta, 3.9);              // 65% of a plain 6-point dock
    }
});

test('reconcile mismatch degrades to bucket-level: no per-item points', () => {
    const tampered = { ...gradeC, restored_points: 9.9 };
    const r = gradeReceiptPresentation({ grade: tampered }, [narrC, baseC]);
    assert.equal(r.verified, false);
    // Membership (published) still renders; numbers do not.
    assert.equal(r.journeys.restored.length, 2);
    for (const row of r.journeys.restored) {
        assert.equal(row.delta, null);
        assert.equal(row.dockPts, null);
    }
    for (const it of r.base.items) assert.equal(it.points, null);
    // The published ledger is always safe to state.
    assert.equal(r.ledger.score, 96);
});

test('same-day visits gate on the Follow-Up purpose', () => {
    const routine = gradeReceiptPresentation({ grade: gradeE1 }, [sameDay('Routine'), baseE]);
    assert.equal(routine.verified, true);
    assert.equal(routine.adjusted, false);
    assert.equal(routine.followups.length, 0);

    const followup = gradeReceiptPresentation({ grade: gradeE2 }, [sameDay('Follow-Up'), baseE]);
    assert.equal(followup.verified, true);
    assert.equal(followup.adjusted, true);
    assert.deepEqual(
        { item: followup.journeys.restored[0].item, delta: followup.journeys.restored[0].delta },
        { item: 35, delta: 1.3 });
});

test('OUT+COS re-check revokes the base credit at full weight, no multiplier', () => {
    const r = gradeReceiptPresentation({ grade: gradeF }, [fupF, baseF]);
    assert.equal(r.verified, true);
    const row = r.journeys.cos[0];
    // 6 full − 4.5 discounted = 1.5 revoked; base item shows its COS chip data
    assert.deepEqual({ item: row.item, delta: row.delta, cosBase: row.cosBase },
        { item: 8, delta: 1.5, cosBase: true });
    assert.equal(r.ledger.added, 1.5);
});

test('missing base row degrades but keeps published totals', () => {
    const r = gradeReceiptPresentation({ grade: gradeB }, [fupB]);  // base row absent
    assert.equal(r.verified, false);
    assert.equal(r.base.found, false);
    assert.equal(r.base.score, 88);
    assert.equal(r.ledger.score, 78);
    // Journeys still list the published membership, numberless.
    assert.equal(r.journeys.restored.length, 1);
    assert.equal(r.journeys.restored[0].delta, null);
});

// ── wiring tripwires (source + CSS stay in step) ────────────────────────

test('the hero circle AND the computed pill both trigger the receipt', () => {
    // Anchor on the method DEFINITIONS (the call sites appear earlier).
    const heroStart = source.indexOf("_gradeHero(g, sparkHtml = '', interactive = true)");
    assert.ok(heroStart !== -1, '_gradeHero definition found');
    const hero = source.slice(heroStart,
        source.indexOf('_newHero(latestView)', heroStart));
    const triggers = hero.match(/data-grade-receipt/g) || [];
    assert.equal(triggers.length, 2, 'circle + pill each carry data-grade-receipt');
    assert.match(hero, /aria-haspopup="dialog"/);
});

test('the full detail render binds the receipt openers', () => {
    assert.match(source, /this\._bindGradeReceipt\(inner, detail\.facility, detail\.inspections\)/);
    // Facility switches and panel closes must not strand an open modal.
    assert.match(source, /_closeDetail\(\)\s*\{\s*this\._closeReceipt\(\)/);
});

test('receipt CSS ships the modal, its dark pairs, and the bottom sheet', () => {
    for (const needle of [
        '.food-receipt-backdrop', '.theme-dark .food-receipt-backdrop',
        '.theme-dark .food-receipt ', 'body.food-receipt-open',
        '.food-receipt-trigger:focus-visible',
        '.theme-dark .food-receipt-delta-pos', '.theme-dark .food-receipt-delta-neg',
        '.theme-dark .food-receipt-cat-rf', '.theme-dark .food-receipt-cat-grp',
        '.theme-dark .food-receipt-narr',
    ]) {
        assert.ok(css.includes(needle), `style.css must contain "${needle}"`);
    }
    // The mobile bottom-sheet variant lives in a max-width media query.
    const sheet = css.slice(css.indexOf('.food-receipt-backdrop'));
    assert.match(sheet, /@media \(max-width: 576px\) \{\s*\n\s*\.food-receipt-backdrop \{ padding: 0; align-items: flex-end; \}/);
});
