// Grade-receipt contract: the modal behind the hero's grade circle mirrors
// the engine's dock math from the published rows, reconciles every derived
// number against the published grade block, and degrades to bucket-level
// (verified:false, no per-item points) on any mismatch. Every fixture's
// grade block here was generated by the REAL engine (cf_lib.facility_grade)
// from these exact inspection docs — engine-certified, not hand-trusted.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const source = readFileSync(
    new URL('../public/static/js/foodDashboard.js', import.meta.url),
    'utf8',
);
const css = readFileSync(
    new URL('../public/static/css/style.css', import.meta.url),
    'utf8',
);
const dashboard = await import(
    `data:text/javascript;base64,${Buffer.from(source).toString('base64')}`
);

const { gradeReceiptPresentation } = dashboard;

// ── engine-certified fixtures ───────────────────────────────────────────

// Case A — unadjusted: repeat-in-text + corrected-on-site on the base.
const baseA = {
    inspection_id: 'B1', date: '2026-03-01', scope: 'broad', score: 85,
    checklist: [
        { item: 8, disposition: 'OUT', violation: true, cos: true },
        { item: 14, disposition: 'OUT', violation: true },
        { item: 35, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 8, text: 'Raw chicken stored over ready-to-eat lettuce' },
        { item: 14, text: 'repeat: handwashing sink blocked by cart' },
        { item: 35, text: 'Floor grout worn behind the line' },
    ],
};
const gradeA = {
    score: 85, letter: 'B', base_score: 85, base_letter: 'B',
    base_date: '2026-03-01', base_inspection_id: 'B1', adjusted: false,
    followups: 0, followup_date: null, narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 0.0,
};

// Case B — adjusted mixed: one restored, one failed, one new-with-repeat,
// one unchecked. Ledger cannot visibly sum (88 + 2.9 − 12 = 78.9 vs 78).
const baseB = {
    inspection_id: 'B1', date: '2026-03-01', scope: 'broad', score: 88,
    checklist: [
        { item: 8, disposition: 'OUT', violation: true, cos: true },
        { item: 14, disposition: 'OUT', violation: true },
        { item: 35, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 8, text: 'Raw chicken stored over ready-to-eat lettuce' },
        { item: 14, text: 'Handwashing sink blocked by cart' },
        { item: 35, text: 'Floor grout worn behind the line' },
    ],
};
const fupB = {
    inspection_id: 'F1', date: '2026-04-01', scope: 'focused',
    purpose: 'Follow-Up', score: 94,
    checklist: [
        { item: 8, disposition: 'IN', compliant: true },
        { item: 14, disposition: 'OUT', violation: true },
        { item: 22, disposition: 'OUT', violation: true, repeat: true },
    ],
    violations: [
        { item: 14, text: 'Sink still blocked' },
        { item: 22, text: 'Sanitizer bucket at 0 ppm, repeat noted' },
    ],
};
const gradeB = {
    score: 78, letter: 'C', base_score: 88, base_letter: 'B',
    base_date: '2026-03-01', base_inspection_id: 'B1', adjusted: true,
    followups: 1, followup_date: '2026-04-01', narrative_followups: 0,
    narrative_items: [], restored_items: [8], failed_items: [14],
    cos_items: [], new_items: [22], unchecked_items: [35],
    restored_points: 2.9, extra_points: 12.0,
};

// Case C — narrative blanket clear: both docks restored by the written verdict.
const baseC = {
    inspection_id: 'B2', date: '2026-02-09', scope: 'broad', score: 88,
    checklist: [{ item: 8, disposition: 'OUT', violation: true },
        { item: 21, disposition: 'OUT', violation: true }],
    violations: [
        { item: 8, text: 'No soap at handwash station' },
        { item: 21, text: 'Cold holding at 47F' },
    ],
};
const narrC = {
    inspection_id: 'N1', date: '2026-04-06', scope: 'unknown',
    purpose: 'Follow-Up', score: 100, checklist: [], violations: [],
    adjudication: { status: 'adjudicated', verdict: 'all_corrected' },
};
const gradeC = {
    score: 96, letter: 'A', base_score: 88, base_letter: 'B',
    base_date: '2026-02-09', base_inspection_id: 'B2', adjusted: true,
    followups: 1, followup_date: '2026-04-06', narrative_followups: 1,
    narrative_items: [8, 21], restored_items: [8, 21], failed_items: [],
    cos_items: [], new_items: [], unchecked_items: [],
    restored_points: 7.8, extra_points: 0.0,
};

// Case D — hybrid focused visit: comments restore items 1 and 3 while the
// structured checklist keeps 22, 52, and 55 OUT. Item 55 appears in both
// channels; the structured OUT governs.
const baseD = {
    inspection_id: 'BH', date: '2026-05-04', scope: 'broad', score: 78,
    checklist: [1, 3, 22, 52, 55].map((item) =>
        ({ item, disposition: 'OUT', violation: true })),
    violations: [1, 3, 22, 52, 55].map((item) => ({ item, text: 'bad' })),
};
const hybridD = {
    inspection_id: 'FH', date: '2026-06-04', scope: 'focused',
    purpose: 'Follow-Up',
    addressed_item_count: 5, out_item_count: 3,
    checklist: [22, 52, 55].map((item) =>
        ({ item, disposition: 'OUT', violation: true })),
    violations: [],
    adjudication: {
        status: 'adjudicated', verdict: 'items',
        items: { 1: 'IN', 3: 'IN', 55: 'IN' },
    },
};
const gradeD = {
    score: 81, letter: 'B', base_score: 78, base_letter: 'C',
    base_date: '2026-05-04', base_inspection_id: 'BH', adjusted: true,
    followups: 1, followup_date: '2026-06-04', narrative_followups: 1,
    narrative_items: [1, 3], restored_items: [1, 3],
    failed_items: [22, 52, 55], cos_items: [], new_items: [],
    unchecked_items: [], restored_points: 7.8, extra_points: 5.0,
};

// Case E — same-day gating: a same-day focused visit adjusts ONLY when its
// purpose marks it a Follow-Up (VDH dates carry no time).
const baseE = {
    inspection_id: 'B3', date: '2026-05-01', scope: 'broad', score: 98,
    checklist: [{ item: 35, disposition: 'OUT', violation: true }],
    violations: [{ item: 35, text: 'Dusty vent hood' }],
};
const sameDay = (purpose) => ({
    inspection_id: 'F2', date: '2026-05-01', scope: 'focused', purpose,
    score: 100, checklist: [{ item: 35, disposition: 'IN', compliant: true }], violations: [],
});
const gradeE1 = {
    score: 98, letter: 'A', base_score: 98, base_letter: 'A',
    base_date: '2026-05-01', base_inspection_id: 'B3', adjusted: false,
    followups: 0, followup_date: null, narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 0.0,
};
const gradeE2 = {
    score: 99, letter: 'A', base_score: 98, base_letter: 'A',
    base_date: '2026-05-01', base_inspection_id: 'B3', adjusted: true,
    followups: 1, followup_date: '2026-05-01', narrative_followups: 0,
    narrative_items: [], restored_items: [35], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 1.3, extra_points: 0.0,
};

// Case F — OUT+COS on a re-check: base credit revoked, full weight, no mult.
const baseF = {
    inspection_id: 'B4', date: '2026-01-10', scope: 'broad', score: 96,
    checklist: [{ item: 8, disposition: 'OUT', violation: true, cos: true }],
    violations: [{ item: 8, text: 'Raw over RTE' }],
};
const fupF = {
    inspection_id: 'F3', date: '2026-02-10', scope: 'focused',
    purpose: 'Follow-Up', score: 94,
    checklist: [{ item: 8, disposition: 'OUT', violation: true, cos: true }],
    violations: [{ item: 8, text: 'Raw over RTE again, moved on the spot' }],
};
const gradeF = {
    score: 94, letter: 'A', base_score: 96, base_letter: 'A',
    base_date: '2026-01-10', base_inspection_id: 'B4', adjusted: true,
    followups: 1, followup_date: '2026-02-10', narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [8],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 1.5,
};

// Case G — several findings under one item number, the shape that used to
// hide behind a "×N findings" chip. Item 8 is cited twice and item 47 three
// times on the base (weights SUM); the re-check restores 8, leaves 47 alone,
// and writes two observations under a new item 61 — which docks ONCE at its
// category weight, however many lines the inspector filed under it.
const baseG = {
    inspection_id: 'B5', date: '2026-03-02', scope: 'broad', score: 82,
    checklist: [
        { item: 8, disposition: 'OUT', violation: true },
        { item: 47, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 8, text: 'Raw chicken stored over ready-to-eat lettuce' },
        { item: 8, text: 'Cut melon held at 51F in the prep-table insert' },
        { item: 47, text: 'Rusted shelving in the walk-in cooler' },
        { item: 47, text: 'Gaskets torn on the reach-in door' },
        { item: 47, text: 'Standing water under the ice machine' },
    ],
};
const fupG = {
    inspection_id: 'F5', date: '2026-04-02', scope: 'focused',
    purpose: 'Follow-Up', score: 96,
    checklist: [
        { item: 8, disposition: 'IN', compliant: true },
        { item: 61, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 61, text: 'Mop sink used to fill the sanitizer bucket' },
        { item: 61, text: 'Chemical spray bottle unlabeled by the dish pit' },
    ],
};
const gradeG = {
    score: 88, letter: 'B', base_score: 82, base_letter: 'B',
    base_date: '2026-03-02', base_inspection_id: 'B5', adjusted: true,
    followups: 1, followup_date: '2026-04-02', narrative_followups: 0,
    narrative_items: [], restored_items: [8], failed_items: [], cos_items: [],
    new_items: [61], unchecked_items: [47], restored_points: 7.8, extra_points: 2.0,
};

// Case H — the Bay Seafood item-47 shape, and the reason the base docket is
// per violation: TWO rows under one item, the first badged COS *and* Repeat,
// the second plain. Row and observation counts pair 1:1, so each finding is
// weighed on its own — 2×1.5×0.75 + 2 = 4.25, where the old item-level merge
// spread the repeat across both and cancelled the COS credit for -6.
const baseH = {
    inspection_id: 'B6', date: '2026-03-03', scope: 'broad', score: 90,
    checklist: [
        { item: 8, disposition: 'OUT', violation: true },
        { item: 47, disposition: 'OUT', violation: true, cos: true, repeat: true },
        { item: 47, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 8, text: 'No soap at the handwash station' },
        { item: 47, text: 'Cardboard lining the under-counter shelves' },
        { item: 47, text: 'Water leaking from the AC hose onto prep surfaces' },
    ],
};
const gradeH = {
    score: 90, letter: 'A', base_score: 90, base_letter: 'A',
    base_date: '2026-03-03', base_inspection_id: 'B6', adjusted: false,
    followups: 0, followup_date: null, narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 0.0,
};

// Case I — case H plus a re-check that clears item 8 and never looks at 47,
// so the split-badge item lands in a JOURNEY group. Journeys resolve per item
// (a re-check publishes one verdict per form line), so that row is an
// aggregate and must not claim the whole item was fixed on site.
const fupI = {
    inspection_id: 'F7', date: '2026-04-04', scope: 'focused',
    purpose: 'Follow-Up', score: 100,
    checklist: [{ item: 8, disposition: 'IN', compliant: true }],
    violations: [],
};
const gradeI = {
    score: 94, letter: 'A', base_score: 90, base_letter: 'A',
    base_date: '2026-03-03', base_inspection_id: 'B6', adjusted: true,
    followups: 1, followup_date: '2026-04-04', narrative_followups: 0,
    narrative_items: [], restored_items: [8], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [47], restored_points: 3.9, extra_points: 0.0,
};

// ── tests ───────────────────────────────────────────────────────────────

test('no grade → no receipt', () => {
    assert.equal(gradeReceiptPresentation({}, []), null);
    assert.equal(gradeReceiptPresentation({ grade: null }, []), null);
});

test('unadjusted receipt verifies and itemizes the base docks', () => {
    const r = gradeReceiptPresentation({ grade: gradeA }, [baseA]);
    assert.equal(r.verified, true);
    assert.equal(r.adjusted, false);
    assert.equal(r.base.found, true);
    assert.equal(r.base.score, 85);
    assert.equal(r.base.items.length, 3);
    const [i8, i14, i35] = r.base.items;
    assert.deepEqual(
        { item: i8.item, points: i8.points, cos: i8.cos, category: i8.category },
        { item: 8, points: 4.5, cos: true, category: 'risk_factor' });
    // repeat detected from the observation TEXT, not just the checklist flag
    assert.deepEqual({ item: i14.item, points: i14.points, repeat: i14.repeat },
        { item: 14, points: 9, repeat: true });
    assert.deepEqual({ item: i35.item, points: i35.points, category: i35.category },
        { item: 35, points: 2, category: 'grp' });
    assert.equal(r.followups.length, 0);
});

test('adjusted receipt derives every journey and reconciles', () => {
    const r = gradeReceiptPresentation({ grade: gradeB }, [fupB, baseB]);
    assert.equal(r.verified, true);
    assert.equal(r.adjusted, true);
    assert.equal(r.followups.length, 1);
    assert.equal(r.followups[0].kind, 'checklist');
    assert.equal(r.followups[0].label, '2/3 OUT');

    const restored = r.journeys.restored[0];
    assert.deepEqual(
        { item: restored.item, delta: restored.delta, dockPts: restored.dockPts },
        { item: 8, delta: 2.9, dockPts: 4.5 });   // 65% of the 4.5 COS'd dock
    const failed = r.journeys.failed[0];
    assert.deepEqual({ item: failed.item, delta: failed.delta },
        { item: 14, delta: 3 });                   // 9 charged − 6 base = 3 more
    const fresh = r.journeys.new[0];
    assert.deepEqual({ item: fresh.item, delta: fresh.delta, repeat: fresh.repeat },
        { item: 22, delta: 9, repeat: true });     // RF × 1.5 repeat flag
    assert.deepEqual(fresh.texts, ['Sanitizer bucket at 0 ppm, repeat noted']);
    const stands = r.journeys.unchecked[0];
    assert.deepEqual({ item: stands.item, dockPts: stands.dockPts },
        { item: 35, dockPts: 2 });

    // 88 + 2.9 − 12 = 78.9 ≠ 78: the round-once footnote must appear.
    assert.equal(r.ledger.exact, false);
    assert.deepEqual(
        { base: r.ledger.baseScore, restored: r.ledger.restored, added: r.ledger.added, score: r.ledger.score },
        { base: 88, restored: 2.9, added: 12, score: 78 });
});

test('narrative blanket clear restores at par and is flagged per item', () => {
    const r = gradeReceiptPresentation({ grade: gradeC }, [narrC, baseC]);
    assert.equal(r.verified, true);
    assert.equal(r.followups[0].kind, 'narrative');
    assert.equal(r.followups[0].label, 'All violations corrected');
    assert.equal(r.journeys.restored.length, 2);
    for (const row of r.journeys.restored) {
        assert.equal(row.narrative, true);
        assert.equal(row.delta, 3.9);              // 65% of a plain 6-point dock
    }
});

test('hybrid follow-up composes comment INs with checklist OUTs once', () => {
    const r = gradeReceiptPresentation({ grade: gradeD }, [hybridD, baseD]);
    assert.equal(r.verified, true);
    assert.equal(r.followups.length, 1);
    assert.equal(r.followups[0].kind, 'hybrid');
    assert.equal(r.followups[0].label, '3/5 OUT');
    assert.deepEqual(r.journeys.restored.map((i) => i.item), [1, 3]);
    assert.deepEqual(r.journeys.failed.map((i) => i.item), [22, 52, 55]);
});

test('reconcile mismatch degrades to bucket-level: no per-item points', () => {
    const tampered = { ...gradeC, restored_points: 9.9 };
    const r = gradeReceiptPresentation({ grade: tampered }, [narrC, baseC]);
    assert.equal(r.verified, false);
    // Membership (published) still renders; numbers do not.
    assert.equal(r.journeys.restored.length, 2);
    for (const row of r.journeys.restored) {
        assert.equal(row.delta, null);
        assert.equal(row.dockPts, null);
    }
    for (const it of r.base.items) assert.equal(it.points, null);
    // The published ledger is always safe to state.
    assert.equal(r.ledger.score, 96);
});

test('same-day visits gate on the Follow-Up purpose', () => {
    const routine = gradeReceiptPresentation({ grade: gradeE1 }, [sameDay('Routine'), baseE]);
    assert.equal(routine.verified, true);
    assert.equal(routine.adjusted, false);
    assert.equal(routine.followups.length, 0);

    const followup = gradeReceiptPresentation({ grade: gradeE2 }, [sameDay('Follow-Up'), baseE]);
    assert.equal(followup.verified, true);
    assert.equal(followup.adjusted, true);
    assert.deepEqual(
        { item: followup.journeys.restored[0].item, delta: followup.journeys.restored[0].delta },
        { item: 35, delta: 1.3 });
});

test('OUT+COS re-check revokes the base credit at full weight, no multiplier', () => {
    const r = gradeReceiptPresentation({ grade: gradeF }, [fupF, baseF]);
    assert.equal(r.verified, true);
    const row = r.journeys.cos[0];
    // 6 full − 4.5 discounted = 1.5 revoked; base item shows its COS chip data
    assert.deepEqual({ item: row.item, delta: row.delta, cosBase: row.cosBase },
        { item: 8, delta: 1.5, cosBase: true });
    assert.equal(r.ledger.added, 1.5);
});

test('missing base row degrades but keeps published totals', () => {
    const r = gradeReceiptPresentation({ grade: gradeB }, [fupB]);  // base row absent
    assert.equal(r.verified, false);
    assert.equal(r.base.found, false);
    assert.equal(r.base.score, 88);
    assert.equal(r.ledger.score, 78);
    // Journeys still list the published membership, numberless.
    assert.equal(r.journeys.restored.length, 1);
    assert.equal(r.journeys.restored[0].delta, null);
});

test('the base docket is one row per violation, each with its own charge', () => {
    const r = gradeReceiptPresentation({ grade: gradeG }, [fupG, baseG]);
    assert.equal(r.verified, true);

    // Five findings under two item numbers -> five rows, not two. Sharing an
    // item is read off the repeated item number and row adjacency, not a
    // dedicated field — sorted by item, filed in document order.
    assert.equal(r.base.items.length, 5);
    assert.deepEqual(r.base.items.map((i) => i.item), [8, 8, 47, 47, 47]);
    // Each carries its own text and its own points.
    const [a, b] = r.base.items;
    assert.equal(a.points, 6);
    assert.equal(b.text, 'Cut melon held at 51F in the prep-table insert');
    assert.equal(r.base.items[4].text, 'Standing water under the ice machine');
    // Item 47's three findings are 2 points each, not one 6-point row.
    assert.deepEqual(r.base.items.slice(2).map((i) => i.points), [2, 2, 2]);

    // Journeys are per FINDING too, symmetric with the docket: a re-check
    // resolves the findings it re-cites by code, so one item can hold a
    // re-cited finding beside an un-recited one. Each row states one finding.
    assert.equal(r.journeys.restored.length, 2);
    assert.deepEqual(r.journeys.restored.map((x) => x.item), [8, 8]);
    assert.deepEqual(r.journeys.restored.map((x) => x.texts.length), [1, 1]);
    assert.equal(r.journeys.unchecked.length, 3);
    assert.deepEqual(r.journeys.unchecked.map((x) => x.item), [47, 47, 47]);
});

test('a journey row states one finding\'s badges, never an item-wide claim', () => {
    const r = gradeReceiptPresentation({ grade: gradeI }, [fupI, baseH]);
    assert.equal(r.verified, true);

    // Item 47 was never re-checked, so both its findings carry — as two rows,
    // because only one was a repeat and only one was fixed on site. An
    // aggregate row could state one of those and would be silent on the other.
    const rows = r.journeys.unchecked;
    assert.equal(rows.length, 2);
    assert.deepEqual(rows.map((x) => x.item), [47, 47]);
    assert.deepEqual(rows.map((x) => x.repeat), [true, false]);
    assert.deepEqual(rows.map((x) => x.cosBase), [true, false]);
    // 2×1.5×0.75 = 2.25 (shown to 1dp) beside a plain 2 — together the 4.25
    // the item carries, but now attributable.
    assert.deepEqual(rows.map((x) => x.dockPts), [2.3, 2]);
    assert.deepEqual(rows.map((x) => x.texts.length), [1, 1]);
});

test('split badges charge each finding on its own, not the item', () => {
    const r = gradeReceiptPresentation({ grade: gradeH }, [baseH]);
    assert.equal(r.verified, true);

    // Item 47: row 1 badged COS+Repeat, row 2 plain. 2x1.5x0.75 + 2 = 4.25,
    // where the old item-level merge spread the repeat and killed the credit
    // for a flat 6.
    const rows = r.base.items.filter((i) => i.item === 47);
    assert.equal(rows.length, 2);
    assert.deepEqual({ points: rows[0].points, repeat: rows[0].repeat, cos: rows[0].cos },
        { points: 2.3, repeat: true, cos: true });      // 2.25, shown to 1dp
    assert.deepEqual({ points: rows[1].points, repeat: rows[1].repeat, cos: rows[1].cos },
        { points: 2, repeat: false, cos: false });
    // The neighbouring plain risk factor is untouched by either badge.
    const rf = r.base.items.find((i) => i.item === 8);
    assert.deepEqual({ points: rf.points, repeat: rf.repeat, cos: rf.cos },
        { points: 6, repeat: false, cos: false });
});

test('a new item docks once no matter how many findings the re-check wrote', () => {
    const r = gradeReceiptPresentation({ grade: gradeG }, [fupG, baseG]);
    const fresh = r.journeys.new[0];
    assert.deepEqual({ item: fresh.item, count: fresh.count, n: fresh.texts.length },
        { item: 61, count: 2, n: 2 });
    assert.equal(fresh.delta, 2);          // ONE retail-practice weight, not two
    // …so the chip must not claim the weights summed.
    assert.equal(fresh.countSums, false);
});

// ── wiring tripwires (source + CSS stay in step) ────────────────────────

test('the hero circle AND the computed pill both trigger the receipt', () => {
    // Anchor on the method DEFINITIONS (the call sites appear earlier).
    const heroStart = source.indexOf("_gradeHero(g, sparkHtml = '', interactive = true)");
    assert.ok(heroStart !== -1, '_gradeHero definition found');
    const hero = source.slice(heroStart,
        source.indexOf('_newHero(latestView)', heroStart));
    const triggers = hero.match(/data-grade-receipt/g) || [];
    assert.equal(triggers.length, 2, 'circle + pill each carry data-grade-receipt');
    assert.match(hero, /aria-haspopup="dialog"/);
});

test('the full detail render binds the receipt openers', () => {
    assert.match(source, /this\._bindGradeReceipt\(inner, detail\.facility, detail\.inspections\)/);
    // Facility switches and panel closes must not strand an open modal.
    assert.match(source, /_closeDetail\(\)\s*\{\s*this\._closeReceipt\(\)/);
});

test('the item row prints every finding, never just the first', () => {
    // Anchor on the name, not the parameter list — this test is about what the
    // row renders, and pinning the signature makes it fail on every unrelated
    // argument added to itemRow.
    const start = source.indexOf('const itemRow = (');
    assert.ok(start !== -1, 'itemRow definition found');
    const row = source.slice(start, source.indexOf('── section 1', start));
    assert.match(row, /texts\.map\(/, 'itemRow renders the whole texts list');
    assert.ok(!/it\.text\b/.test(row), 'no single-text fallback survives');
    assert.ok(css.includes('.food-receipt-item-texts'),
        'style.css ships the multi-finding list');
});

// Case K — one item, two findings; the follow-up re-cites ONE of them by its
// regulatory code. The engine joins the verdict to that finding and leaves its
// neighbour unchecked, so item 55 belongs to two buckets at once.
const baseK = {
    inspection_id: 'K1', date: '2026-05-19', scope: 'broad', score: 96,
    checklist: [
        { item: 55, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 55, code: '12VAC5-421-3180.A',
            text: 'Heavy grease buildup on floors under the cook line' },
        { item: 55, code: '12VAC5-421-3170',
            text: 'Floor tiles cracked and grout worn through the kitchen' },
    ],
};
const fupK = {
    inspection_id: 'K2', date: '2026-06-15', scope: 'focused',
    purpose: 'Follow-Up',
    checklist: [{ item: 55, disposition: 'OUT', violation: true }],
    violations: [
        { item: 55, code: '12VAC5-421-3170',
            text: 'Floor tiles cracked and grout worn through the kitchen' },
    ],
};
const gradeK = {
    score: 95, letter: 'A', base_score: 96, base_letter: 'A',
    base_date: '2026-05-19', base_inspection_id: 'K1', adjusted: true,
    followups: 1, followup_date: '2026-06-15', narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [55],
    cos_items: [], new_items: [], unchecked_items: [55],
    restored_findings: [], failed_findings: [1], cos_findings: [],
    unchecked_findings: [0],
    restored_points: 0.0, extra_points: 1.0,
};

test('a re-cited finding fails while its neighbour goes unchecked', () => {
    const r = gradeReceiptPresentation({ grade: gradeK }, [fupK, baseK]);
    assert.equal(r.verified, true, 'per-finding membership reconciles');

    // One item, two fates. Item-level resolution could express only one.
    const [failed] = r.journeys.failed;
    const [carried] = r.journeys.unchecked;
    assert.equal(failed.item, 55);
    assert.equal(carried.item, 55);
    assert.match(failed.texts[0], /Floor tiles cracked/);
    assert.match(carried.texts[0], /Heavy grease buildup/);

    // The re-cited finding revokes to full ×1.5 (2 → 3, so +1); the spared one
    // carries its face value and adds nothing.
    assert.equal(failed.delta, 1);
    assert.equal(carried.dockPts, 2);
    assert.equal(carried.delta, null);
    assert.equal(r.ledger.added, 1);
});

test('legacy payloads without *_findings still expand to per-finding rows', () => {
    // Published before per-finding resolution: every finding under an item
    // shared one fate, so expanding the item's dock reproduces what it meant.
    const legacy = { ...gradeK, unchecked_items: [], failed_items: [55] };
    delete legacy.failed_findings;
    delete legacy.unchecked_findings;
    delete legacy.restored_findings;
    delete legacy.cos_findings;
    const r = gradeReceiptPresentation({ grade: legacy }, [fupK, baseK]);
    assert.equal(r.journeys.failed.length, 2, 'both findings under item 55');
    assert.deepEqual(r.journeys.failed.map((x) => x.item), [55, 55]);
});

// Case H — a hybrid follow-up whose checklist names ONE of item 55's two
// findings by code while its adjudicated comment clears the rest. The two
// channels compose per finding: tiles fail, grease restores, and item 55
// lands in both buckets.
const baseH2 = {
    inspection_id: 'H1', date: '2026-05-19', scope: 'broad', score: 90,
    checklist: [
        { item: 22, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 22, code: '12VAC5-421-820.A.2',
            text: 'Cold holding above 41F in the prep unit' },
        { item: 55, code: '12VAC5-421-3180.A',
            text: 'Heavy grease buildup on floors under the cook line' },
        { item: 55, code: '12VAC5-421-3170',
            text: 'Floor tiles cracked and grout worn through the kitchen' },
    ],
};
const fupH2 = {
    inspection_id: 'H2', date: '2026-06-15', scope: 'focused',
    purpose: 'Follow-Up',
    checklist: [
        { item: 22, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 22, code: '12VAC5-421-820.A.2' },
        { item: 55, code: '12VAC5-421-3170' },
    ],
    adjudication: { schema: 1, status: 'adjudicated', verdict: 'all_corrected',
        tier: 'blanket_all', method: 'regex' },
};
const gradeH2 = {
    score: 87, letter: 'B', base_score: 90, base_letter: 'A',
    base_date: '2026-05-19', base_inspection_id: 'H1', adjusted: true,
    followups: 1, followup_date: '2026-06-15', narrative_followups: 1,
    narrative_items: [55], restored_items: [55], failed_items: [22, 55],
    cos_items: [], new_items: [], unchecked_items: [],
    restored_findings: [1], failed_findings: [0, 2], cos_findings: [],
    unchecked_findings: [], restored_points: 1.3, extra_points: 4.0,
};

test('a comment covers the findings the checklist did not name', () => {
    const r = gradeReceiptPresentation({ grade: gradeH2 }, [fupH2, baseH2]);
    assert.equal(r.verified, true, 'per-finding composition reconciles');

    // Item 55 in two buckets, one finding each way — the item-level collision
    // rule discarded the comment for 55 entirely and carried the grease.
    const [restored] = r.journeys.restored;
    assert.equal(restored.item, 55);
    assert.match(restored.texts[0], /Heavy grease buildup/);
    assert.equal(restored.narrative, true, 'sourced from the comment');
    assert.deepEqual(r.journeys.failed.map((x) => x.item), [22, 55]);
    assert.match(r.journeys.failed[1].texts[0], /Floor tiles cracked/);
    assert.equal(r.journeys.unchecked.length, 0, 'every finding got a word');
});

// Case J — a `findings` verdict: the comment names citations by code, so it
// credits one of item 55's two findings and leaves the other carrying. An
// `items` verdict could only have said one word for both.
const baseJ = {
    inspection_id: 'J1', date: '2026-05-19', scope: 'broad', score: 90,
    checklist: [
        { item: 55, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
        { item: 10, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 55, code: '12VAC5-421-3180.A',
            text: 'Heavy grease buildup on floors' },
        { item: 55, code: '12VAC5-421-3170',
            text: 'Floor tiles cracked and grout worn' },
        { item: 10, code: '12VAC5-421-2310.B',
            text: 'Bar handwashing sink used as a dump sink' },
    ],
};
const fupJ = {
    inspection_id: 'J2', date: '2026-06-15', scope: 'unknown',
    purpose: 'Follow-Up', checklist: [], violations: [],
    adjudication: {
        schema: 1, status: 'adjudicated', verdict: 'findings',
        tier: 'residue', method: 'llm',
        findings: [{ item: 55, code: '3170', word: 'IN' },
            { item: 10, code: '2310.B', word: 'IN' }],
    },
};
const gradeJ = {
    score: 95, letter: 'A', base_score: 90, base_letter: 'A',
    base_date: '2026-05-19', base_inspection_id: 'J1', adjusted: true,
    followups: 1, followup_date: '2026-06-15', narrative_followups: 1,
    narrative_items: [10, 55], restored_items: [10, 55], failed_items: [],
    cos_items: [], new_items: [], unchecked_items: [55],
    restored_findings: [1, 2], failed_findings: [], cos_findings: [],
    unchecked_findings: [0], restored_points: 5.2, extra_points: 0.0,
};

test('a findings verdict credits only the citations it names', () => {
    const r = gradeReceiptPresentation({ grade: gradeJ }, [fupJ, baseJ]);
    assert.equal(r.verified, true, 'code-joined membership reconciles');

    assert.deepEqual(r.journeys.restored.map((x) => x.item), [55, 10]);
    assert.match(r.journeys.restored[0].texts[0], /Floor tiles cracked/);
    // The grease was never named — same item number, different citation.
    assert.equal(r.journeys.unchecked.length, 1);
    assert.match(r.journeys.unchecked[0].texts[0], /Heavy grease buildup/);
    assert.equal(r.journeys.unchecked[0].item, 55);
});

test('a findings verdict ignores a code the base does not carry', () => {
    const stale = {
        ...fupJ,
        adjudication: { ...fupJ.adjudication,
            findings: [{ item: 55, code: '9999', word: 'IN' }] },
    };
    const r = gradeReceiptPresentation({ grade: gradeJ }, [stale, baseJ]);
    // Nothing resolves, so the derivation stops matching the published block —
    // the receipt degrades rather than inventing a credit.
    assert.equal(r.verified, false);
});

// Case P — The Boathouse at Rocketts Landing 2025-04-15, the real record that
// surfaced the gap. Base carries the dotted-prefixed form ("12VAC5-421-
// 820.A.2"); the follow-up comment writes the district's OWN raw-fragment
// notation ("22-820(A2)"), which an LLM census judge quoted verbatim. Before
// the fix neither finding resolved -- both are engine-certified restored here.
const baseP = {
    inspection_id: 'K1', date: '2026-05-19', scope: 'broad', score: 88,
    checklist: [
        { item: 22, disposition: 'OUT', violation: true },
        { item: 25, disposition: 'OUT', violation: true },
    ],
    violations: [
        { item: 22, code: '12VAC5-421-820.A.2', text: 'Prep unit cold holding' },
        { item: 25, code: '12VAC5-421-930.B', text: 'No disclosure asterisks' },
    ],
};
const fupP = {
    inspection_id: 'K2', date: '2026-06-15', scope: 'unknown',
    purpose: 'Follow-Up', checklist: [], violations: [],
    adjudication: {
        schema: 1, status: 'adjudicated', verdict: 'findings',
        tier: 'residue', method: 'llm',
        findings: [{ item: 22, code: '820(A2)', word: 'IN' },
            { item: 25, code: '930(B)', word: 'IN' }],
    },
};
const gradeP = {
    score: 96, letter: 'A', base_score: 88, base_letter: 'B',
    base_date: '2026-05-19', base_inspection_id: 'K1', adjusted: true,
    followups: 1, followup_date: '2026-06-15', narrative_followups: 1,
    narrative_items: [22, 25], restored_items: [22, 25], failed_items: [],
    cos_items: [], new_items: [], unchecked_items: [],
    restored_findings: [0, 1], failed_findings: [], cos_findings: [],
    unchecked_findings: [], restored_points: 7.8, extra_points: 0.0,
};

test('a parenthetical citation resolves against the base\'s dotted code', () => {
    const r = gradeReceiptPresentation({ grade: gradeP }, [fupP, baseP]);
    assert.equal(r.verified, true, 'both findings resolve and reconcile');
    assert.deepEqual(r.journeys.restored.map((x) => x.item), [22, 25]);
    assert.equal(r.journeys.unchecked.length, 0);
});

test('a revoked on-site credit is not badged as if it still applied', () => {
    // failed and cos both charge `full` — the base COS discount is gone by the
    // time either group renders. Badging it under a heading that says "any
    // on-site credit revoked" advertises a discount the arithmetic already took
    // back. restored and unchecked charge the DISCOUNTED dock, so there the
    // chip is true and stays.
    const start = source.indexOf('const creditHeld = (bucket) =>');
    assert.ok(start !== -1, 'creditHeld predicate found');
    const pred = source.slice(start, source.indexOf(';', start));
    for (const held of ['restored', 'unchecked']) {
        assert.ok(pred.includes(`'${held}'`), `${held} must keep the credit`);
    }
    for (const revoked of ['failed', 'cos']) {
        assert.ok(!pred.includes(`'${revoked}'`),
            `${revoked} must not keep the credit`);
    }
    // The chip is gated on it, and the bucket is threaded down to the row.
    assert.match(source, /it\.cosBase && creditHeld\(bucket\) \?/);
    assert.match(source, /itemRow\(row, delta\(row\), bucket\)/);
});

test('journey rows drop the per-violation weight from the category chip', () => {
    // In a journey group the charge is the whole item at full weight ×1.5, so a
    // per-violation "−6" beside a "−4.5 more" states two numbers that do not
    // reconcile. The base docket keeps the value — there it IS the row's charge.
    assert.match(source, /const catChip = \(category, points = true\) =>/);
    assert.match(source, /points \? 'risk factor −6' : 'risk factor'/);
    assert.match(source, /points \? 'retail practice −2' : 'retail practice'/);
    const itemRowSrc = source.slice(source.indexOf('const itemRow = ('),
        source.indexOf('── section 1'));
    assert.match(itemRowSrc, /body, deltaHtml, false\);/,
        'journey rows suppress the point value');
});

test('receipt CSS ships the modal, its dark pairs, and the bottom sheet', () => {
    for (const needle of [
        '.food-receipt-backdrop', '.theme-dark .food-receipt-backdrop',
        '.theme-dark .food-receipt ', 'body.food-receipt-open',
        '.food-receipt-trigger:focus-visible',
        '.theme-dark .food-receipt-delta-pos', '.theme-dark .food-receipt-delta-neg',
        '.theme-dark .food-receipt-cat-rf', '.theme-dark .food-receipt-cat-grp',
        '.theme-dark .food-receipt-narr',
    ]) {
        assert.ok(css.includes(needle), `style.css must contain "${needle}"`);
    }
    // The mobile bottom-sheet variant lives in a max-width media query.
    const sheet = css.slice(css.indexOf('.food-receipt-backdrop'));
    assert.match(sheet, /@media \(max-width: 576px\) \{\s*\n\s*\.food-receipt-backdrop \{ padding: 0; align-items: flex-end; \}/);
});
