/** The COMMITTED lite roster's shape — a data tripwire, not a code test.
 *
 *  Every other suite here tests source. This one tests the artifact:
 *  `public/data/facilities.json`, the ~5 MB public payload that ships to
 *  cleanplateva.com on every push to main. It is regenerated by
 *  `cf_export_site.py --mode lite` on whichever machine happens to run the
 *  pipeline — and a machine with a STALE cground-skills checkout writes an
 *  older payload shape over a current one. Nothing in CouchDB is wrong when
 *  that happens, so no upstream check catches it.
 *
 *  The failure that earns this file: lite's `mobile` boolean (11th field,
 *  2026-07-24) is what makes the "Show mobile food units" switch work on the
 *  public tier. The switch is no longer in the `.food-mode-lite` hide-list,
 *  so a roster without `mobile` renders it VISIBLE AND INERT — 1,862 trucks
 *  silently back on the default map, toggle doing nothing. That is precisely
 *  the failure "Show new" shipped with from #26 until 2026-07-21.
 *
 *  Assertions are structural, never counts: a data refresh must never turn
 *  this suite red. If the lite contract genuinely changes, update FIELDS in
 *  the same commit that changes `_shape_lite`.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const roster = JSON.parse(readFileSync(
    new URL('../public/data/facilities.json', import.meta.url), 'utf8'));

// The lite identity contract (cf_export_site._shape_lite). Judgment fields
// are absent BY DESIGN — lite is a finder, not a grader.
const FIELDS = [
    'address', 'address2', 'approx', 'city', 'is_restaurant', 'lat', 'lon',
    'mobile', 'name', 'permit_id', 'tenant', 'zip',
];

test('the committed roster is a lite payload with facilities in it', () => {
    assert.equal(roster.available, true);
    assert.equal(roster.mode, 'lite');
    assert.ok(Array.isArray(roster.facilities));
    assert.ok(roster.facilities.length > 1000,
        `only ${roster.facilities.length} facilities — a truncated export?`);
});

test('every record carries exactly the 12-field lite contract', () => {
    const seen = new Set();
    for (const f of roster.facilities) for (const k of Object.keys(f)) seen.add(k);
    assert.deepEqual([...seen].sort(), FIELDS,
        'the committed lite roster no longer matches _shape_lite — either a '
        + 'stale export overwrote it, or the contract changed and this list '
        + 'needs updating in the same commit');
    // Spot-check completeness per record, not just across the union: a record
    // missing `mobile` is exactly the stale-export symptom.
    for (const f of roster.facilities.slice(0, 2000)) {
        assert.deepEqual(Object.keys(f).sort(), FIELDS, f.permit_id);
    }
});

test('mobile is a real boolean and actually flags trucks', () => {
    let trucks = 0;
    for (const f of roster.facilities) {
        assert.equal(typeof f.mobile, 'boolean', f.permit_id);
        if (f.mobile) trucks++;
    }
    // Virginia always has mobile food units on the roster; zero means the
    // exporter emitted the key but never set it (a half-stale export).
    assert.ok(trucks > 100,
        `only ${trucks} mobile units flagged — the mobile predicate looks broken`);
    // And they must be a minority, or the predicate is over-matching and the
    // default view would hide the whole map.
    assert.ok(trucks < roster.facilities.length * 0.25,
        `${trucks} of ${roster.facilities.length} flagged mobile — over-matching?`);
});

test('tenant routes the VDH permit link to the right district', () => {
    // The permit deep link is tenant-scoped. A roster without `tenant` sends
    // every district-claimed facility to the /virginia/ aggregate, which shows
    // a stale husk — the exact bug Golden Unicorn surfaced (2026-07-24). Lite's
    // ONE call to action is that link, so a missing tenant breaks the tier's
    // whole purpose.
    let districted = 0;
    for (const f of roster.facilities) {
        assert.equal(typeof f.tenant, 'string', f.permit_id);
        assert.match(f.tenant, /^(virginia|va-[a-z-]+)$/, f.permit_id);
        if (f.tenant !== 'virginia') districted++;
    }
    // Post-union-rescrape, districts claim the overwhelming majority. A roster
    // that is mostly `virginia` means the export ran against pre-union docs.
    assert.ok(districted > roster.facilities.length * 0.5,
        `only ${districted} of ${roster.facilities.length} district-claimed — `
        + 'did this export run before the tenant field was persisted?');
});

test('no judgment field leaked into the public tier', () => {
    // Lite stays judgment-free: no scores, grades, dates, statuses, history.
    const banned = ['grade', 'score_trend', 'trend', 'latest',
        'latest_assessment', 'status', 'permit_type', 'declining',
        'inspection_count', 'newly_permitted'];
    for (const f of roster.facilities.slice(0, 5000)) {
        for (const key of banned) {
            assert.ok(!(key in f), `${key} leaked onto lite record ${f.permit_id}`);
        }
    }
});
