/**
 * Grade-receipt contract (§7 pure-derivation port, CRVa-M2): the modal
 * behind the hero's grade circle mirrors the engine's dock math from the
 * published rows, reconciles every derived number against the published
 * grade block, and degrades to bucket-level (verified:false, no per-item
 * points) on any mismatch. Every fixture's grade block was generated by
 * the REAL engine (cf_lib.facility_grade) from these exact inspection docs
 * — engine-certified, not hand-trusted. Ported from
 * tests/grade-receipt.test.mjs (its behavioral half; the old design's
 * source/CSS wiring scans are superseded by the CRV component suites).
 */
import { expect, test } from 'vitest'
import { gradeReceiptPresentation } from '../../app/data/receipt'
import type { Inspection } from '../../app/data/types'

// Fixture checklists are partial rows (the engine's own test shape); the
// client's decode fills the rest on the real click path.
type RowStub = { item: number | null; disposition: string } & Record<string, unknown>
const cl = (rows: RowStub[]) => rows as unknown as Inspection['checklist']

// ── engine-certified fixtures ───────────────────────────────────────────

const baseA: Inspection = {
    inspection_id: 'B1', date: '2026-03-01', scope: 'broad', score: 85,
    checklist: cl([
        { item: 8, disposition: 'OUT', violation: true, cos: true },
        { item: 14, disposition: 'OUT', violation: true },
        { item: 35, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 8, text: 'Raw chicken stored over ready-to-eat lettuce' },
        { item: 14, text: 'repeat: handwashing sink blocked by cart' },
        { item: 35, text: 'Floor grout worn behind the line' },
    ],
}
const gradeA = {
    score: 85, letter: 'B', base_score: 85, base_letter: 'B',
    base_date: '2026-03-01', base_inspection_id: 'B1', adjusted: false,
    followups: 0, followup_date: null, narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 0.0,
}

const baseB: Inspection = {
    inspection_id: 'B1', date: '2026-03-01', scope: 'broad', score: 88,
    checklist: cl([
        { item: 8, disposition: 'OUT', violation: true, cos: true },
        { item: 14, disposition: 'OUT', violation: true },
        { item: 35, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 8, text: 'Raw chicken stored over ready-to-eat lettuce' },
        { item: 14, text: 'Handwashing sink blocked by cart' },
        { item: 35, text: 'Floor grout worn behind the line' },
    ],
}
const fupB: Inspection = {
    inspection_id: 'F1', date: '2026-04-01', scope: 'focused',
    purpose: 'Follow-Up', score: 94,
    checklist: cl([
        { item: 8, disposition: 'IN', compliant: true },
        { item: 14, disposition: 'OUT', violation: true },
        { item: 22, disposition: 'OUT', violation: true, repeat: true },
    ]),
    violations: [
        { item: 14, text: 'Sink still blocked' },
        { item: 22, text: 'Sanitizer bucket at 0 ppm, repeat noted' },
    ],
}
const gradeB = {
    score: 78, letter: 'C', base_score: 88, base_letter: 'B',
    base_date: '2026-03-01', base_inspection_id: 'B1', adjusted: true,
    followups: 1, followup_date: '2026-04-01', narrative_followups: 0,
    narrative_items: [], restored_items: [8], failed_items: [14],
    cos_items: [], new_items: [22], unchecked_items: [35],
    restored_points: 2.9, extra_points: 12.0,
}

const baseC: Inspection = {
    inspection_id: 'B2', date: '2026-02-09', scope: 'broad', score: 88,
    checklist: cl([
        { item: 8, disposition: 'OUT', violation: true },
        { item: 21, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 8, text: 'No soap at handwash station' },
        { item: 21, text: 'Cold holding at 47F' },
    ],
}
const narrC: Inspection = {
    inspection_id: 'N1', date: '2026-04-06', scope: 'unknown',
    purpose: 'Follow-Up', score: 100, checklist: [], violations: [],
    adjudication: { status: 'adjudicated', verdict: 'all_corrected' },
}
const gradeC = {
    score: 96, letter: 'A', base_score: 88, base_letter: 'B',
    base_date: '2026-02-09', base_inspection_id: 'B2', adjusted: true,
    followups: 1, followup_date: '2026-04-06', narrative_followups: 1,
    narrative_items: [8, 21], restored_items: [8, 21], failed_items: [],
    cos_items: [], new_items: [], unchecked_items: [],
    restored_points: 7.8, extra_points: 0.0,
}

const baseD: Inspection = {
    inspection_id: 'BH', date: '2026-05-04', scope: 'broad', score: 78,
    checklist: cl([1, 3, 22, 52, 55].map((item) =>
        ({ item, disposition: 'OUT', violation: true }))),
    violations: [1, 3, 22, 52, 55].map((item) => ({ item, text: 'bad' })),
}
const hybridD: Inspection = {
    inspection_id: 'FH', date: '2026-06-04', scope: 'focused',
    purpose: 'Follow-Up',
    addressed_item_count: 5, out_item_count: 3,
    checklist: cl([22, 52, 55].map((item) =>
        ({ item, disposition: 'OUT', violation: true }))),
    violations: [],
    adjudication: {
        status: 'adjudicated', verdict: 'items',
        items: { 1: 'IN', 3: 'IN', 55: 'IN' },
    },
}
const gradeD = {
    score: 81, letter: 'B', base_score: 78, base_letter: 'C',
    base_date: '2026-05-04', base_inspection_id: 'BH', adjusted: true,
    followups: 1, followup_date: '2026-06-04', narrative_followups: 1,
    narrative_items: [1, 3], restored_items: [1, 3],
    failed_items: [22, 52, 55], cos_items: [], new_items: [],
    unchecked_items: [], restored_points: 7.8, extra_points: 5.0,
}

const baseE: Inspection = {
    inspection_id: 'B3', date: '2026-05-01', scope: 'broad', score: 98,
    checklist: cl([{ item: 35, disposition: 'OUT', violation: true }]),
    violations: [{ item: 35, text: 'Dusty vent hood' }],
}
const sameDay = (purpose: string): Inspection => ({
    inspection_id: 'F2', date: '2026-05-01', scope: 'focused', purpose,
    score: 100,
    checklist: cl([{ item: 35, disposition: 'IN', compliant: true }]),
    violations: [],
})
const gradeE1 = {
    score: 98, letter: 'A', base_score: 98, base_letter: 'A',
    base_date: '2026-05-01', base_inspection_id: 'B3', adjusted: false,
    followups: 0, followup_date: null, narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 0.0,
}
const gradeE2 = {
    score: 99, letter: 'A', base_score: 98, base_letter: 'A',
    base_date: '2026-05-01', base_inspection_id: 'B3', adjusted: true,
    followups: 1, followup_date: '2026-05-01', narrative_followups: 0,
    narrative_items: [], restored_items: [35], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 1.3, extra_points: 0.0,
}

const baseF: Inspection = {
    inspection_id: 'B4', date: '2026-01-10', scope: 'broad', score: 96,
    checklist: cl([{ item: 8, disposition: 'OUT', violation: true, cos: true }]),
    violations: [{ item: 8, text: 'Raw over RTE' }],
}
const fupF: Inspection = {
    inspection_id: 'F3', date: '2026-02-10', scope: 'focused',
    purpose: 'Follow-Up', score: 94,
    checklist: cl([{ item: 8, disposition: 'OUT', violation: true, cos: true }]),
    violations: [{ item: 8, text: 'Raw over RTE again, moved on the spot' }],
}
const gradeF = {
    score: 94, letter: 'A', base_score: 96, base_letter: 'A',
    base_date: '2026-01-10', base_inspection_id: 'B4', adjusted: true,
    followups: 1, followup_date: '2026-02-10', narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [8],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 1.5,
}

const baseG: Inspection = {
    inspection_id: 'B5', date: '2026-03-02', scope: 'broad', score: 82,
    checklist: cl([
        { item: 8, disposition: 'OUT', violation: true },
        { item: 47, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 8, text: 'Raw chicken stored over ready-to-eat lettuce' },
        { item: 8, text: 'Cut melon held at 51F in the prep-table insert' },
        { item: 47, text: 'Rusted shelving in the walk-in cooler' },
        { item: 47, text: 'Gaskets torn on the reach-in door' },
        { item: 47, text: 'Standing water under the ice machine' },
    ],
}
const fupG: Inspection = {
    inspection_id: 'F5', date: '2026-04-02', scope: 'focused',
    purpose: 'Follow-Up', score: 96,
    checklist: cl([
        { item: 8, disposition: 'IN', compliant: true },
        { item: 61, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 61, text: 'Mop sink used to fill the sanitizer bucket' },
        { item: 61, text: 'Chemical spray bottle unlabeled by the dish pit' },
    ],
}
const gradeG = {
    score: 88, letter: 'B', base_score: 82, base_letter: 'B',
    base_date: '2026-03-02', base_inspection_id: 'B5', adjusted: true,
    followups: 1, followup_date: '2026-04-02', narrative_followups: 0,
    narrative_items: [], restored_items: [8], failed_items: [], cos_items: [],
    new_items: [61], unchecked_items: [47], restored_points: 7.8, extra_points: 2.0,
}

const baseH: Inspection = {
    inspection_id: 'B6', date: '2026-03-03', scope: 'broad', score: 90,
    checklist: cl([
        { item: 8, disposition: 'OUT', violation: true },
        { item: 47, disposition: 'OUT', violation: true, cos: true, repeat: true },
        { item: 47, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 8, text: 'No soap at the handwash station' },
        { item: 47, text: 'Cardboard lining the under-counter shelves' },
        { item: 47, text: 'Water leaking from the AC hose onto prep surfaces' },
    ],
}
const gradeH = {
    score: 90, letter: 'A', base_score: 90, base_letter: 'A',
    base_date: '2026-03-03', base_inspection_id: 'B6', adjusted: false,
    followups: 0, followup_date: null, narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [], restored_points: 0.0, extra_points: 0.0,
}

const fupI: Inspection = {
    inspection_id: 'F7', date: '2026-04-04', scope: 'focused',
    purpose: 'Follow-Up', score: 100,
    checklist: cl([{ item: 8, disposition: 'IN', compliant: true }]),
    violations: [],
}
const gradeI = {
    score: 94, letter: 'A', base_score: 90, base_letter: 'A',
    base_date: '2026-03-03', base_inspection_id: 'B6', adjusted: true,
    followups: 1, followup_date: '2026-04-04', narrative_followups: 0,
    narrative_items: [], restored_items: [8], failed_items: [], cos_items: [],
    new_items: [], unchecked_items: [47], restored_points: 3.9, extra_points: 0.0,
}

const baseK: Inspection = {
    inspection_id: 'K1', date: '2026-05-19', scope: 'broad', score: 96,
    checklist: cl([
        { item: 55, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 55, code: '12VAC5-421-3180.A', text: 'Heavy grease buildup on floors under the cook line' },
        { item: 55, code: '12VAC5-421-3170', text: 'Floor tiles cracked and grout worn through the kitchen' },
    ],
}
const fupK: Inspection = {
    inspection_id: 'K2', date: '2026-06-15', scope: 'focused',
    purpose: 'Follow-Up',
    checklist: cl([{ item: 55, disposition: 'OUT', violation: true }]),
    violations: [
        { item: 55, code: '12VAC5-421-3170', text: 'Floor tiles cracked and grout worn through the kitchen' },
    ],
}
const gradeK = {
    score: 95, letter: 'A', base_score: 96, base_letter: 'A',
    base_date: '2026-05-19', base_inspection_id: 'K1', adjusted: true,
    followups: 1, followup_date: '2026-06-15', narrative_followups: 0,
    narrative_items: [], restored_items: [], failed_items: [55],
    cos_items: [], new_items: [], unchecked_items: [55],
    restored_findings: [], failed_findings: [1], cos_findings: [],
    unchecked_findings: [0],
    restored_points: 0.0, extra_points: 1.0,
}

const baseH2: Inspection = {
    inspection_id: 'H1', date: '2026-05-19', scope: 'broad', score: 90,
    checklist: cl([
        { item: 22, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 22, code: '12VAC5-421-820.A.2', text: 'Cold holding above 41F in the prep unit' },
        { item: 55, code: '12VAC5-421-3180.A', text: 'Heavy grease buildup on floors under the cook line' },
        { item: 55, code: '12VAC5-421-3170', text: 'Floor tiles cracked and grout worn through the kitchen' },
    ],
}
const fupH2: Inspection = {
    inspection_id: 'H2', date: '2026-06-15', scope: 'focused',
    purpose: 'Follow-Up',
    checklist: cl([
        { item: 22, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 22, code: '12VAC5-421-820.A.2' },
        { item: 55, code: '12VAC5-421-3170' },
    ],
    adjudication: {
        schema: 1, status: 'adjudicated', verdict: 'all_corrected',
        tier: 'blanket_all', method: 'regex',
    } as Inspection['adjudication'],
}
const gradeH2 = {
    score: 87, letter: 'B', base_score: 90, base_letter: 'A',
    base_date: '2026-05-19', base_inspection_id: 'H1', adjusted: true,
    followups: 1, followup_date: '2026-06-15', narrative_followups: 1,
    narrative_items: [55], restored_items: [55], failed_items: [22, 55],
    cos_items: [], new_items: [], unchecked_items: [],
    restored_findings: [1], failed_findings: [0, 2], cos_findings: [],
    unchecked_findings: [], restored_points: 1.3, extra_points: 4.0,
}

const baseJ: Inspection = {
    inspection_id: 'J1', date: '2026-05-19', scope: 'broad', score: 90,
    checklist: cl([
        { item: 55, disposition: 'OUT', violation: true },
        { item: 55, disposition: 'OUT', violation: true },
        { item: 10, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 55, code: '12VAC5-421-3180.A', text: 'Heavy grease buildup on floors' },
        { item: 55, code: '12VAC5-421-3170', text: 'Floor tiles cracked and grout worn' },
        { item: 10, code: '12VAC5-421-2310.B', text: 'Bar handwashing sink used as a dump sink' },
    ],
}
const fupJ: Inspection = {
    inspection_id: 'J2', date: '2026-06-15', scope: 'unknown',
    purpose: 'Follow-Up', checklist: [], violations: [],
    adjudication: {
        schema: 1, status: 'adjudicated', verdict: 'findings',
        tier: 'residue', method: 'llm',
        findings: [
            { item: 55, code: '3170', word: 'IN' },
            { item: 10, code: '2310.B', word: 'IN' },
        ],
    } as Inspection['adjudication'],
}
const gradeJ = {
    score: 95, letter: 'A', base_score: 90, base_letter: 'A',
    base_date: '2026-05-19', base_inspection_id: 'J1', adjusted: true,
    followups: 1, followup_date: '2026-06-15', narrative_followups: 1,
    narrative_items: [10, 55], restored_items: [10, 55], failed_items: [],
    cos_items: [], new_items: [], unchecked_items: [55],
    restored_findings: [1, 2], failed_findings: [], cos_findings: [],
    unchecked_findings: [0], restored_points: 5.2, extra_points: 0.0,
}

const baseP: Inspection = {
    inspection_id: 'K1', date: '2026-05-19', scope: 'broad', score: 88,
    checklist: cl([
        { item: 22, disposition: 'OUT', violation: true },
        { item: 25, disposition: 'OUT', violation: true },
    ]),
    violations: [
        { item: 22, code: '12VAC5-421-820.A.2', text: 'Prep unit cold holding' },
        { item: 25, code: '12VAC5-421-930.B', text: 'No disclosure asterisks' },
    ],
}
const fupP: Inspection = {
    inspection_id: 'K2', date: '2026-06-15', scope: 'unknown',
    purpose: 'Follow-Up', checklist: [], violations: [],
    adjudication: {
        schema: 1, status: 'adjudicated', verdict: 'findings',
        tier: 'residue', method: 'llm',
        findings: [
            { item: 22, code: '820(A2)', word: 'IN' },
            { item: 25, code: '930(B)', word: 'IN' },
        ],
    } as Inspection['adjudication'],
}
const gradeP = {
    score: 96, letter: 'A', base_score: 88, base_letter: 'B',
    base_date: '2026-05-19', base_inspection_id: 'K1', adjusted: true,
    followups: 1, followup_date: '2026-06-15', narrative_followups: 1,
    narrative_items: [22, 25], restored_items: [22, 25], failed_items: [],
    cos_items: [], new_items: [], unchecked_items: [],
    restored_findings: [0, 1], failed_findings: [], cos_findings: [],
    unchecked_findings: [], restored_points: 7.8, extra_points: 0.0,
}

// ── tests ───────────────────────────────────────────────────────────────

test('no grade → no receipt', () => {
    expect(gradeReceiptPresentation({}, [])).toBeNull()
    expect(gradeReceiptPresentation({ grade: null as never }, [])).toBeNull()
})

test('unadjusted receipt verifies and itemizes the base docks', () => {
    const r = gradeReceiptPresentation({ grade: gradeA }, [baseA])
    expect(r?.verified).toBe(true)
    expect(r?.adjusted).toBe(false)
    expect(r?.base.found).toBe(true)
    expect(r?.base.score).toBe(85)
    expect(r?.base.items).toHaveLength(3)
    const [i8, i14, i35] = r?.base.items ?? []
    expect({ item: i8?.item, points: i8?.points, cos: i8?.cos, category: i8?.category })
        .toEqual({ item: 8, points: 4.5, cos: true, category: 'risk_factor' })
    // repeat detected from the observation TEXT, not just the checklist flag
    expect({ item: i14?.item, points: i14?.points, repeat: i14?.repeat })
        .toEqual({ item: 14, points: 9, repeat: true })
    expect({ item: i35?.item, points: i35?.points, category: i35?.category })
        .toEqual({ item: 35, points: 2, category: 'grp' })
    expect(r?.followups).toHaveLength(0)
})

test('adjusted receipt derives every journey and reconciles', () => {
    const r = gradeReceiptPresentation({ grade: gradeB }, [fupB, baseB])
    expect(r?.verified).toBe(true)
    expect(r?.adjusted).toBe(true)
    expect(r?.followups).toHaveLength(1)
    expect(r?.followups[0]?.kind).toBe('checklist')
    expect(r?.followups[0]?.label).toBe('2/3 OUT')

    const restored = r?.journeys.restored[0]
    expect({ item: restored?.item, delta: restored?.delta, dockPts: restored?.dockPts })
        .toEqual({ item: 8, delta: 2.9, dockPts: 4.5 })  // 65% of the 4.5 COS'd dock
    const failed = r?.journeys.failed[0]
    expect({ item: failed?.item, delta: failed?.delta })
        .toEqual({ item: 14, delta: 3 })                 // 9 charged − 6 base = 3 more
    const fresh = r?.journeys.new[0]
    expect({ item: fresh?.item, delta: fresh?.delta, repeat: fresh?.repeat })
        .toEqual({ item: 22, delta: 9, repeat: true })   // RF × 1.5 repeat flag
    expect(fresh?.texts).toEqual(['Sanitizer bucket at 0 ppm, repeat noted'])
    const stands = r?.journeys.unchecked[0]
    expect({ item: stands?.item, dockPts: stands?.dockPts })
        .toEqual({ item: 35, dockPts: 2 })

    // 88 + 2.9 − 12 = 78.9 ≠ 78: the round-once footnote must appear.
    expect(r?.ledger.exact).toBe(false)
    expect({
        base: r?.ledger.baseScore, restored: r?.ledger.restored,
        added: r?.ledger.added, score: r?.ledger.score,
    }).toEqual({ base: 88, restored: 2.9, added: 12, score: 78 })
})

test('narrative blanket clear restores at par and is flagged per item', () => {
    const r = gradeReceiptPresentation({ grade: gradeC }, [narrC, baseC])
    expect(r?.verified).toBe(true)
    expect(r?.followups[0]?.kind).toBe('narrative')
    expect(r?.followups[0]?.label).toBe('All violations corrected')
    expect(r?.journeys.restored).toHaveLength(2)
    for (const row of r?.journeys.restored ?? []) {
        expect(row.narrative).toBe(true)
        expect(row.delta).toBe(3.9)                     // 65% of a plain 6-point dock
    }
})

test('hybrid follow-up composes comment INs with checklist OUTs once', () => {
    const r = gradeReceiptPresentation({ grade: gradeD }, [hybridD, baseD])
    expect(r?.verified).toBe(true)
    expect(r?.followups).toHaveLength(1)
    expect(r?.followups[0]?.kind).toBe('hybrid')
    expect(r?.followups[0]?.label).toBe('3/5 OUT')
    expect(r?.journeys.restored.map((i) => i.item)).toEqual([1, 3])
    expect(r?.journeys.failed.map((i) => i.item)).toEqual([22, 52, 55])
})

test('reconcile mismatch degrades to bucket-level: no per-item points', () => {
    const tampered = { ...gradeC, restored_points: 9.9 }
    const r = gradeReceiptPresentation({ grade: tampered }, [narrC, baseC])
    expect(r?.verified).toBe(false)
    // Membership (published) still renders; numbers do not.
    expect(r?.journeys.restored).toHaveLength(2)
    for (const row of r?.journeys.restored ?? []) {
        expect(row.delta).toBeNull()
        expect(row.dockPts).toBeNull()
    }
    for (const it of r?.base.items ?? []) expect(it.points).toBeNull()
    // The published ledger is always safe to state.
    expect(r?.ledger.score).toBe(96)
})

test('same-day visits gate on the Follow-Up purpose', () => {
    const routine = gradeReceiptPresentation({ grade: gradeE1 }, [sameDay('Routine'), baseE])
    expect(routine?.verified).toBe(true)
    expect(routine?.adjusted).toBe(false)
    expect(routine?.followups).toHaveLength(0)

    const followup = gradeReceiptPresentation({ grade: gradeE2 }, [sameDay('Follow-Up'), baseE])
    expect(followup?.verified).toBe(true)
    expect(followup?.adjusted).toBe(true)
    expect({
        item: followup?.journeys.restored[0]?.item,
        delta: followup?.journeys.restored[0]?.delta,
    }).toEqual({ item: 35, delta: 1.3 })
})

test('OUT+COS re-check revokes the base credit at full weight, no multiplier', () => {
    const r = gradeReceiptPresentation({ grade: gradeF }, [fupF, baseF])
    expect(r?.verified).toBe(true)
    const row = r?.journeys.cos[0]
    // 6 full − 4.5 discounted = 1.5 revoked; base item shows its COS chip data
    expect({ item: row?.item, delta: row?.delta, cosBase: row?.cosBase })
        .toEqual({ item: 8, delta: 1.5, cosBase: true })
    expect(r?.ledger.added).toBe(1.5)
})

test('missing base row degrades but keeps published totals', () => {
    const r = gradeReceiptPresentation({ grade: gradeB }, [fupB]) // base row absent
    expect(r?.verified).toBe(false)
    expect(r?.base.found).toBe(false)
    expect(r?.base.score).toBe(88)
    expect(r?.ledger.score).toBe(78)
    // Journeys still list the published membership, numberless.
    expect(r?.journeys.restored).toHaveLength(1)
    expect(r?.journeys.restored[0]?.delta).toBeNull()
})

test('the base docket is one row per violation, each with its own charge', () => {
    const r = gradeReceiptPresentation({ grade: gradeG }, [fupG, baseG])
    expect(r?.verified).toBe(true)

    // Five findings under two item numbers → five rows, not two.
    expect(r?.base.items).toHaveLength(5)
    expect(r?.base.items.map((i) => i.item)).toEqual([8, 8, 47, 47, 47])
    const [a, b] = r?.base.items ?? []
    expect(a?.points).toBe(6)
    expect(b?.text).toBe('Cut melon held at 51F in the prep-table insert')
    expect(r?.base.items[4]?.text).toBe('Standing water under the ice machine')
    // Item 47's three findings are 2 points each, not one 6-point row.
    expect(r?.base.items.slice(2).map((i) => i.points)).toEqual([2, 2, 2])

    // Journeys are per FINDING too, symmetric with the docket.
    expect(r?.journeys.restored).toHaveLength(2)
    expect(r?.journeys.restored.map((x) => x.item)).toEqual([8, 8])
    expect(r?.journeys.restored.map((x) => x.texts.length)).toEqual([1, 1])
    expect(r?.journeys.unchecked).toHaveLength(3)
    expect(r?.journeys.unchecked.map((x) => x.item)).toEqual([47, 47, 47])
})

test("a journey row states one finding's badges, never an item-wide claim", () => {
    const r = gradeReceiptPresentation({ grade: gradeI }, [fupI, baseH])
    expect(r?.verified).toBe(true)

    // Item 47 was never re-checked, so both its findings carry — as two
    // rows, because only one was a repeat and only one was fixed on site.
    const rows = r?.journeys.unchecked ?? []
    expect(rows).toHaveLength(2)
    expect(rows.map((x) => x.item)).toEqual([47, 47])
    expect(rows.map((x) => x.repeat)).toEqual([true, false])
    expect(rows.map((x) => x.cosBase)).toEqual([true, false])
    // 2×1.5×0.75 = 2.25 (shown to 1dp) beside a plain 2.
    expect(rows.map((x) => x.dockPts)).toEqual([2.3, 2])
    expect(rows.map((x) => x.texts.length)).toEqual([1, 1])
})

test('split badges charge each finding on its own, not the item', () => {
    const r = gradeReceiptPresentation({ grade: gradeH }, [baseH])
    expect(r?.verified).toBe(true)

    // Item 47: row 1 badged COS+Repeat, row 2 plain. 2×1.5×0.75 + 2 = 4.25.
    const rows = (r?.base.items ?? []).filter((i) => i.item === 47)
    expect(rows).toHaveLength(2)
    expect({ points: rows[0]?.points, repeat: rows[0]?.repeat, cos: rows[0]?.cos })
        .toEqual({ points: 2.3, repeat: true, cos: true })   // 2.25, shown to 1dp
    expect({ points: rows[1]?.points, repeat: rows[1]?.repeat, cos: rows[1]?.cos })
        .toEqual({ points: 2, repeat: false, cos: false })
    // The neighbouring plain risk factor is untouched by either badge.
    const rf = (r?.base.items ?? []).find((i) => i.item === 8)
    expect({ points: rf?.points, repeat: rf?.repeat, cos: rf?.cos })
        .toEqual({ points: 6, repeat: false, cos: false })
})

test('a new item docks once no matter how many findings the re-check wrote', () => {
    const r = gradeReceiptPresentation({ grade: gradeG }, [fupG, baseG])
    const fresh = r?.journeys.new[0]
    expect({ item: fresh?.item, count: fresh?.count, n: fresh?.texts.length })
        .toEqual({ item: 61, count: 2, n: 2 })
    expect(fresh?.delta).toBe(2)        // ONE retail-practice weight, not two
    // …so the chip must not claim the weights summed.
    expect(fresh?.countSums).toBe(false)
})

test('a re-cited finding fails while its neighbour goes unchecked', () => {
    const r = gradeReceiptPresentation({ grade: gradeK }, [fupK, baseK])
    expect(r?.verified).toBe(true)

    // One item, two fates. Item-level resolution could express only one.
    const [failed] = r?.journeys.failed ?? []
    const [carried] = r?.journeys.unchecked ?? []
    expect(failed?.item).toBe(55)
    expect(carried?.item).toBe(55)
    expect(failed?.texts[0]).toMatch(/Floor tiles cracked/)
    expect(carried?.texts[0]).toMatch(/Heavy grease buildup/)

    // The re-cited finding revokes to full ×1.5 (2 → 3, so +1).
    expect(failed?.delta).toBe(1)
    expect(carried?.dockPts).toBe(2)
    expect(carried?.delta).toBeNull()
    expect(r?.ledger.added).toBe(1)
})

test('legacy payloads without *_findings still expand to per-finding rows', () => {
    const legacy: Record<string, unknown> = { ...gradeK, unchecked_items: [], failed_items: [55] }
    delete legacy.failed_findings
    delete legacy.unchecked_findings
    delete legacy.restored_findings
    delete legacy.cos_findings
    const r = gradeReceiptPresentation({ grade: legacy }, [fupK, baseK])
    expect(r?.journeys.failed).toHaveLength(2)
    expect(r?.journeys.failed.map((x) => x.item)).toEqual([55, 55])
})

test('a comment covers the findings the checklist did not name', () => {
    const r = gradeReceiptPresentation({ grade: gradeH2 }, [fupH2, baseH2])
    expect(r?.verified).toBe(true)

    // Item 55 in two buckets, one finding each way.
    const [restored] = r?.journeys.restored ?? []
    expect(restored?.item).toBe(55)
    expect(restored?.texts[0]).toMatch(/Heavy grease buildup/)
    expect(restored?.narrative).toBe(true)
    expect(r?.journeys.failed.map((x) => x.item)).toEqual([22, 55])
    expect(r?.journeys.failed[1]?.texts[0]).toMatch(/Floor tiles cracked/)
    expect(r?.journeys.unchecked).toHaveLength(0)
})

test('a findings verdict credits only the citations it names', () => {
    const r = gradeReceiptPresentation({ grade: gradeJ }, [fupJ, baseJ])
    expect(r?.verified).toBe(true)

    expect(r?.journeys.restored.map((x) => x.item)).toEqual([55, 10])
    expect(r?.journeys.restored[0]?.texts[0]).toMatch(/Floor tiles cracked/)
    // The grease was never named — same item number, different citation.
    expect(r?.journeys.unchecked).toHaveLength(1)
    expect(r?.journeys.unchecked[0]?.texts[0]).toMatch(/Heavy grease buildup/)
    expect(r?.journeys.unchecked[0]?.item).toBe(55)
})

test('a findings verdict ignores a code the base does not carry', () => {
    const stale: Inspection = {
        ...fupJ,
        adjudication: {
            ...fupJ.adjudication,
            findings: [{ item: 55, code: '9999', word: 'IN' }],
        } as Inspection['adjudication'],
    }
    const r = gradeReceiptPresentation({ grade: gradeJ }, [stale, baseJ])
    // Nothing resolves, so the derivation stops matching the published
    // block — the receipt degrades rather than inventing a credit.
    expect(r?.verified).toBe(false)
})

test("a parenthetical citation resolves against the base's dotted code", () => {
    const r = gradeReceiptPresentation({ grade: gradeP }, [fupP, baseP])
    expect(r?.verified).toBe(true)
    expect(r?.journeys.restored.map((x) => x.item)).toEqual([22, 25])
    expect(r?.journeys.unchecked).toHaveLength(0)
})
